name: Nextjs Deployment in Vercel

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: amondnet/vercel-action@v25 # deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
        #   github-token: ${{ secrets.GITHUB_TOKEN }} # Optional
          vercel-args: --prod # Optional
          vercel-org-id: ${{ secrets.ORG_ID}} # Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} # Required
        #   working-directory: ./

      - name: Deployment Successful Notification
        if: success()
        run: echo "âœ… Successfully deployed tag ${{ github.ref_name }} to Vercel Production!"
